{{- if .Values.ingress.internal.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "atlas.selectorLabels" . | nindent 4 }}
  {{- with .Values.annotations.ingress }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "atlas.fullname" . }}-internal
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: {{ .Values.ingress.internal.className }}
  rules:
    {{- toYaml .Values.ingress.rules | nindent 4 }}
{{- end }}
---
{{- if .Values.ingress.external.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "atlas.selectorLabels" . | nindent 4 }}
  {{- with .Values.annotations.ingress }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "atlas.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: {{ .Values.ingress.external.className }}
  rules:
    {{- toYaml .Values.ingress.rules | nindent 4 }}
{{- end }}